name: build

on:
  push: {}
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: pnpm

      - name: install deps
        run: pnpm install

      - name: lint
        run: pnpm lint -- -CI

      - name: audit
        run: pnpm audit -P

      - name: browser coverage
        run: node ./browserCheck.js

      - name: build
        run: pnpm build
        env:
          CI: false
